config/routes.rb
Rails.application.routes.draw do
  root "salaries#index"
  resources :salaries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/salary.rb
class Salary < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController
  def index
    @salaries = Salary.all
  end


  def show
    @salary = Salary.find(params[:id])  
  end

  def new
    @salary = Salary.new
  end

  def create
    @salary = Salary.new(salary_params)
    @salary.save
    redirect_to salaries_path
  end

  def edit
    @salary = Salary.find(params[:id])  
  end

  

  def update
    @salary = Salary.find(params[:id])
    @salary.update(salary_params)
    redirect_to salaries_path
  end

  

end

private

  def salary_params
    params.require(:salary).permit(:name, :s_name, :salary_amount)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/salary_helper.rb
module SalaryHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MySalary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/salaries/edit.html.erb
<h1>Edit page</h1>

<%= form_for @salary do |f| %>
  <p>
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label "Second name" %> <br>
    <%= f.text_field :s_name %>
  </p>
  <p>
    <%= f.label "Salary" %> <br>
    <%= f.number_field :salary_amount %>
  </p>

  <p>
    <%= f.submit  %>
  </p>
<% end %>

app/views/salaries/index.html.erb
<h1><%= pluralize(@salaries.size, 'Salary') %></h1>

<% @salaries.each do |salary| %>
  <p><%= link_to(salary.name, salary) %></p>
<% end %>

<%= link_to "Add salary", new_salary_path %>

app/views/salaries/new.html.erb
<h1>Add salary</h1>

<%= form_for @salary do |f| %>
  <p>
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label "Second name" %> <br>
    <%= f.text_field :s_name %>
  </p>
  <p>
    <%= f.label "Salary" %> <br>
    <%= f.number_field :salary_amount %>
  </p>

  <p>
    <%= f.submit  %>
  </p>
<% end %>

app/views/salaries/show.html.erb
<h1><%= @salary.name %>`s salary</h1>

<p>Total salary</p>
<b><%= @salary.salary_amount %> USD</b>
<br>
<p><%= link_to("Main page", salaries_path) %>
 ||
   <%= link_to("Edit page", edit_salary_path) %>
</p>